dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
install:
    - pip install .[tests]
    - pip install coveralls
script:
    - pytest
    - make -C docs html
after_success:
  - coveralls
